<?php
/**
 * ..................................................................................
 *                                 index.phtml                                       *
 * ..................................................................................*
 *
 * This is a template file. A template file is used by view blocks in order to show
 * the content in frontend. Multiple blocks can use the same template simultaneously.
 *
 * File     : index.phtml
 * Content  : HTML + PHP
 * Location : app/design/core/default/index/index.phtml
 */
?>
<?php
var_dump($this);
echo $this->getContent();