<?php
/**
 * SimpleMage
 *...................................................................................
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License that is bundled with this package
 * in the file LICENSE_SM.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Core
 * @package    Core_Deafult
 * @copyright  Copyright (c) 2015
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php
/**
 * @see Core_Default_View_Index_Index
 */
?>

<!--
	This section shows how to call memeber methods from view class
-->
<h1><?php echo $this->Heading() ?></h1>
<p><?php echo $this->DefaultContent() ?></p>

<!--
	This section will show you how can we collect a data that is set via controller
	(Using magic setter).
-->

<p>The Controller says : "<?php echo $this->getContent() ?>"</p>
